events {
    worker_connections 64;
}

http {
    upstream user_service {
        server user-service:8000;
    }

    upstream metrics_service {
        server ingestion-service:8001;
    }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://user_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Correlation-ID $request_id;
        }

        location /api/metrics/ {
            proxy_pass http://metrics_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Correlation-ID $request_id;
        }

        location /health {
            return 200 '{"status": "healthy", "service": "nginx"}';
            add_header Content-Type application/json;
        }
    }
}
